### ISSUE TITLE
mutate: reset mutant by id

### ISSUE THREAD

**Issue by pokgak** [joakim-brannstrom/dextool#1172]
Currently, it is possible to reset all mutant with a certain mutant operator using the `--mutant` option but after extending my test case, I just want to reset a single alive mutant to unknown using its id so that for the next test run it will be retested without going through all other unrelated tests to save some time. I tried the following commands but it seems to me that this is not supported(?):

Using `resetMutant` operation:
```
dextool mutate admin --operation resetMutant --id 87
info: Using /home/pokgak/git/RIOT-mutate-dev/mutate/dextool_mutate.sqlite3
```

Using `markMutant` operation, there seems to also be a bug as I cannot find docs on what the missing mutText is:
```
dextool mutate admin --operation markMutant --id 87 --to-status unknown --rationale test
info: Using /home/pokgak/git/RIOT-mutate-dev/mutate/dextool_mutate.sqlite3
error: error 19: NOT NULL constraint failed: marked_mutant.mutText
error: exiting...
```

**Comment by joakim-brannstrom** [comment]
That is a reasonable request to be able to manually reset a mutant by its ID. I'll add it and improve the doc for markMutant.

I think markMutant need some more documentation. It is a bit of advanced feature that lets you mark a mutant with whatever status you want and the tool keeps track of this. If it is ever lost then the tool informs you and askes you to re-"glue" the marking. It is fore those cases where it isn't applicable/impossible to add a ```// NOMUT``` because the source code is not possible to change. It is *frozen*, qualified or other reasons.

**Comment by joakim-brannstrom** [comment]
> dextool mutate admin --operation markMutant --id 87 --to-status unknown --rationale test
> info: Using /home/pokgak/git/RIOT-mutate-dev/mutate/dextool_mutate.sqlite3
> error: error 19: NOT NULL constraint failed: marked_mutant.mutText
> error: exiting...
> ```

#1174 should fix NOT NULL

**Comment by pokgak** [comment]
> #1174 should fix NOT NULL

Confirmed fix working with `dextool mutate admin --operation markMutant --id 20 --to-status unknown --rationale test`. With that I'll consider this issue fixed though I prefer to use `dextool mutate admin --operation resetMutant --id 87` as that is more straightforward. I'll leave that up to you to decide. Thank you for your time :)
