### ISSUE TITLE
Libclang and llvm-dev is required but not stated in the dependencies

### ISSUE THREAD

**Issue by JKRT** [joakim-brannstrom/dextool#896]
The example installation command is: 

`sudo apt install build-essential cmake llvm-4.0 llvm-4.0-dev clang-4.0 libclang-4.0-dev libsqlite3-dev`

If this is the case should not both llvm-dev **and** libclang-dev be stated among the dependencies as well?

Best of regards,

John

**Comment by joakim-brannstrom** [comment]
Do you have a good suggestion for how to phrase the dependencies in the readme to make it clearer?

Currently:
 * [llvm](http://releases.llvm.org/download.html) (4.0+, both libclang and LLVM is needed)

**Comment by JKRT** [comment]
> 
> 
> Do you have a good suggestion for how to phrase the dependencies in the readme to make it clearer?
> 
> Currently:
> 
>     * [llvm](http://releases.llvm.org/download.html) (4.0+, both libclang and LLVM is needed)

Are there not certain things in dev that differs from the regular one?

**Comment by peatersson** [comment]
Can't we just list all the packages the ubuntu-row below is listing? 

Something in the lines of:
-     llvm (4.0+, both libclang and LLVM is needed, see below)
-     llvm-XYZ-dev (4.0+)
-     libclang-XYZ-dev (4.0+)
-     cmake (3.5+)
-     D compiler (dmd 2.081.2+, ldc 1.11.0+)
-     sqlite3 (3.19.3-3+)

I am guessing that the problem here is that the list of dependencies differs, if you just read the bullet points, compared to the "for ubuntu users" list.

By specifying explicitly, we remove any kind of uncertainty.
