### ISSUE TITLE
mutate: improve visualization of sdl mutants

### ISSUE THREAD

**Issue by christoffer-nylen** [joakim-brannstrom/dextool#907]
Scenario 1: Working with a slow test suite
* Statement deletion (sdl) is being used + other common mutation operators.
* File `a.c` has been mutated for 1 day and still got 6 days remaining.
* File `a.c` contains a function `f()` with 200 LoC.
* The entire body of `f()` has been mutated/removed and killed by a (multi-line) sdl mutant.
* 10 additional mutants inside the function body of `f()` have been killed by other mutants, for example single-line sdl mutants.
* The user would like use the html report to examine the 10 mutants inside `f()` that was killed.

Scenario 2: Pull-request review

Result:
* The entire function body for `f()` looks green because of the killed multi-line sdl mutant.

Problems:
* Overview: When the whole function becomes red / green the user perceives it as very "noisy" and difficult to get an overview of how well tested the pull request is.
* Detail: It is not possible to see the result for the 10 sdl mutants inside the 200 LoC function -> It is hard to assess the quality of that function.

Suggestions:
 * Use `sdl` for traditional single-line statement deletion
 * Something like `sdlx` for extreme mutation for the remaining types?
 * Make sure that both `sdl` and `sdlx` are available as filter alternatives in the html report.

**Comment by christoffer-nylen** [comment]
Suggestion from a user:

> Replace stmtdel color from `function body` to `function name` or the initial `{`. When the whole function becomes red / green I perceive it as very "noisy" and difficult to get an overview of how well tested my pull request is.

**Comment by joakim-brannstrom** [comment]
closing as there are no plans to change sdl as is suggested in this issue as of now.

 * Use sdl for traditional single-line statement deletion
Traditional SDL is too slow because it turns into too many mutants thus it will never be implemented.

 * Something like sdlx for extreme mutation for the remaining types?
 * Make sure that both sdl and sdlx are available as filter alternatives in the html report.
The impl. of SDL is it is today is the only one that will be supported.

There may be improvement enhancements to how SDLs, or rather multi-line mutants are visualized but so far (with the latest fixes) it seems to be good enough.
